// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.0
// source: notify-service.proto

package notify

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotyEmpty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NotyEmpty) Reset() {
	*x = NotyEmpty{}
	mi := &file_notify_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotyEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotyEmpty) ProtoMessage() {}

func (x *NotyEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_notify_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotyEmpty.ProtoReflect.Descriptor instead.
func (*NotyEmpty) Descriptor() ([]byte, []int) {
	return file_notify_service_proto_rawDescGZIP(), []int{0}
}

type NoteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NoteUuid string `protobuf:"bytes,1,opt,name=note_uuid,json=noteUuid,proto3" json:"note_uuid,omitempty"`
}

func (x *NoteReq) Reset() {
	*x = NoteReq{}
	mi := &file_notify_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteReq) ProtoMessage() {}

func (x *NoteReq) ProtoReflect() protoreflect.Message {
	mi := &file_notify_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteReq.ProtoReflect.Descriptor instead.
func (*NoteReq) Descriptor() ([]byte, []int) {
	return file_notify_service_proto_rawDescGZIP(), []int{1}
}

func (x *NoteReq) GetNoteUuid() string {
	if x != nil {
		return x.NoteUuid
	}
	return ""
}

type NoteCount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *NoteCount) Reset() {
	*x = NoteCount{}
	mi := &file_notify_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteCount) ProtoMessage() {}

func (x *NoteCount) ProtoReflect() protoreflect.Message {
	mi := &file_notify_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteCount.ProtoReflect.Descriptor instead.
func (*NoteCount) Descriptor() ([]byte, []int) {
	return file_notify_service_proto_rawDescGZIP(), []int{2}
}

func (x *NoteCount) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type NoteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsRead bool `protobuf:"varint,1,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
}

func (x *NoteResp) Reset() {
	*x = NoteResp{}
	mi := &file_notify_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteResp) ProtoMessage() {}

func (x *NoteResp) ProtoReflect() protoreflect.Message {
	mi := &file_notify_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteResp.ProtoReflect.Descriptor instead.
func (*NoteResp) Descriptor() ([]byte, []int) {
	return file_notify_service_proto_rawDescGZIP(), []int{3}
}

func (x *NoteResp) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

type NotifyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmployerUuid string `protobuf:"bytes,1,opt,name=employer_uuid,json=employerUuid,proto3" json:"employer_uuid,omitempty"`
}

func (x *NotifyReq) Reset() {
	*x = NotifyReq{}
	mi := &file_notify_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyReq) ProtoMessage() {}

func (x *NotifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_notify_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyReq.ProtoReflect.Descriptor instead.
func (*NotifyReq) Descriptor() ([]byte, []int) {
	return file_notify_service_proto_rawDescGZIP(), []int{4}
}

func (x *NotifyReq) GetEmployerUuid() string {
	if x != nil {
		return x.EmployerUuid
	}
	return ""
}

type VacancyNotyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VacancyUuid string `protobuf:"bytes,1,opt,name=vacancy_uuid,json=vacancyUuid,proto3" json:"vacancy_uuid,omitempty"`
}

func (x *VacancyNotyReq) Reset() {
	*x = VacancyNotyReq{}
	mi := &file_notify_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VacancyNotyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VacancyNotyReq) ProtoMessage() {}

func (x *VacancyNotyReq) ProtoReflect() protoreflect.Message {
	mi := &file_notify_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VacancyNotyReq.ProtoReflect.Descriptor instead.
func (*VacancyNotyReq) Descriptor() ([]byte, []int) {
	return file_notify_service_proto_rawDescGZIP(), []int{5}
}

func (x *VacancyNotyReq) GetVacancyUuid() string {
	if x != nil {
		return x.VacancyUuid
	}
	return ""
}

type EmployerNotyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmployerUuid string `protobuf:"bytes,1,opt,name=employer_uuid,json=employerUuid,proto3" json:"employer_uuid,omitempty"`
}

func (x *EmployerNotyResp) Reset() {
	*x = EmployerNotyResp{}
	mi := &file_notify_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployerNotyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployerNotyResp) ProtoMessage() {}

func (x *EmployerNotyResp) ProtoReflect() protoreflect.Message {
	mi := &file_notify_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployerNotyResp.ProtoReflect.Descriptor instead.
func (*EmployerNotyResp) Descriptor() ([]byte, []int) {
	return file_notify_service_proto_rawDescGZIP(), []int{6}
}

func (x *EmployerNotyResp) GetEmployerUuid() string {
	if x != nil {
		return x.EmployerUuid
	}
	return ""
}

var File_notify_service_proto protoreflect.FileDescriptor

var file_notify_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a,
	0x13, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2d, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0b, 0x0a, 0x09, 0x4e, 0x6f, 0x74, 0x79, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x26, 0x0a, 0x07, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09,
	0x6e, 0x6f, 0x74, 0x65, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6e, 0x6f, 0x74, 0x65, 0x55, 0x75, 0x69, 0x64, 0x22, 0x21, 0x0a, 0x09, 0x4e, 0x6f, 0x74,
	0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x23, 0x0a, 0x08,
	0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x72,
	0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x52, 0x65, 0x61,
	0x64, 0x22, 0x30, 0x0a, 0x09, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x12, 0x23,
	0x0a, 0x0d, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x72, 0x55,
	0x75, 0x69, 0x64, 0x22, 0x33, 0x0a, 0x0e, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x4e, 0x6f,
	0x74, 0x79, 0x52, 0x65, 0x71, 0x12, 0x21, 0x0a, 0x0c, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79,
	0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x76, 0x61, 0x63,
	0x61, 0x6e, 0x63, 0x79, 0x55, 0x75, 0x69, 0x64, 0x22, 0x37, 0x0a, 0x10, 0x45, 0x6d, 0x70, 0x6c,
	0x6f, 0x79, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x23, 0x0a, 0x0d,
	0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x72, 0x55, 0x75, 0x69,
	0x64, 0x32, 0xa8, 0x02, 0x0a, 0x13, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x1d, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x64, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x73, 0x42, 0x79, 0x4e, 0x6f, 0x74, 0x79, 0x12, 0x12, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x15,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x3e, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x55,
	0x6e, 0x72, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x15,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x3d, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x61, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x10, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x1a, 0x11, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4e, 0x6f, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x46, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x45, 0x6d, 0x70, 0x6c, 0x6f,
	0x79, 0x65, 0x72, 0x42, 0x79, 0x56, 0x61, 0x63, 0x12, 0x17, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x4e, 0x6f, 0x74, 0x79, 0x52, 0x65,
	0x71, 0x1a, 0x19, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x45, 0x6d, 0x70, 0x6c,
	0x6f, 0x79, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x42, 0x12, 0x5a, 0x10,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_notify_service_proto_rawDescOnce sync.Once
	file_notify_service_proto_rawDescData = file_notify_service_proto_rawDesc
)

func file_notify_service_proto_rawDescGZIP() []byte {
	file_notify_service_proto_rawDescOnce.Do(func() {
		file_notify_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_notify_service_proto_rawDescData)
	})
	return file_notify_service_proto_rawDescData
}

var file_notify_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_notify_service_proto_goTypes = []any{
	(*NotyEmpty)(nil),        // 0: service.NotyEmpty
	(*NoteReq)(nil),          // 1: service.NoteReq
	(*NoteCount)(nil),        // 2: service.NoteCount
	(*NoteResp)(nil),         // 3: service.NoteResp
	(*NotifyReq)(nil),        // 4: service.NotifyReq
	(*VacancyNotyReq)(nil),   // 5: service.VacancyNotyReq
	(*EmployerNotyResp)(nil), // 6: service.EmployerNotyResp
	(*Notifications)(nil),    // 7: models.Notifications
}
var file_notify_service_proto_depIdxs = []int32{
	4, // 0: service.NotificationService.GetAllAppliedCandidatesByNoty:input_type -> service.NotifyReq
	4, // 1: service.NotificationService.GetAllUnreadCount:input_type -> service.NotifyReq
	1, // 2: service.NotificationService.UpdateReadNotification:input_type -> service.NoteReq
	5, // 3: service.NotificationService.GetEmployerByVac:input_type -> service.VacancyNotyReq
	7, // 4: service.NotificationService.GetAllAppliedCandidatesByNoty:output_type -> models.Notifications
	7, // 5: service.NotificationService.GetAllUnreadCount:output_type -> models.Notifications
	3, // 6: service.NotificationService.UpdateReadNotification:output_type -> service.NoteResp
	6, // 7: service.NotificationService.GetEmployerByVac:output_type -> service.EmployerNotyResp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notify_service_proto_init() }
func file_notify_service_proto_init() {
	if File_notify_service_proto != nil {
		return
	}
	file_notify_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_notify_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notify_service_proto_goTypes,
		DependencyIndexes: file_notify_service_proto_depIdxs,
		MessageInfos:      file_notify_service_proto_msgTypes,
	}.Build()
	File_notify_service_proto = out.File
	file_notify_service_proto_rawDesc = nil
	file_notify_service_proto_goTypes = nil
	file_notify_service_proto_depIdxs = nil
}
