// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.0
// source: notify-service.proto

package notify

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotesDbEmpty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NotesDbEmpty) Reset() {
	*x = NotesDbEmpty{}
	mi := &file_notify_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotesDbEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotesDbEmpty) ProtoMessage() {}

func (x *NotesDbEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_notify_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotesDbEmpty.ProtoReflect.Descriptor instead.
func (*NotesDbEmpty) Descriptor() ([]byte, []int) {
	return file_notify_service_proto_rawDescGZIP(), []int{0}
}

var File_notify_service_proto protoreflect.FileDescriptor

var file_notify_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a,
	0x13, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2d, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0e, 0x0a, 0x0c, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x44, 0x62, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x32, 0x57, 0x0a, 0x13, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x15, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x44,
	0x62, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x15, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x12, 0x5a,
	0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_notify_service_proto_rawDescOnce sync.Once
	file_notify_service_proto_rawDescData = file_notify_service_proto_rawDesc
)

func file_notify_service_proto_rawDescGZIP() []byte {
	file_notify_service_proto_rawDescOnce.Do(func() {
		file_notify_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_notify_service_proto_rawDescData)
	})
	return file_notify_service_proto_rawDescData
}

var file_notify_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_notify_service_proto_goTypes = []any{
	(*NotesDbEmpty)(nil),  // 0: service.NotesDbEmpty
	(*Notifications)(nil), // 1: models.Notifications
}
var file_notify_service_proto_depIdxs = []int32{
	0, // 0: service.NotificationService.GetNotifications:input_type -> service.NotesDbEmpty
	1, // 1: service.NotificationService.GetNotifications:output_type -> models.Notifications
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notify_service_proto_init() }
func file_notify_service_proto_init() {
	if File_notify_service_proto != nil {
		return
	}
	file_notify_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_notify_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notify_service_proto_goTypes,
		DependencyIndexes: file_notify_service_proto_depIdxs,
		MessageInfos:      file_notify_service_proto_msgTypes,
	}.Build()
	File_notify_service_proto = out.File
	file_notify_service_proto_rawDesc = nil
	file_notify_service_proto_goTypes = nil
	file_notify_service_proto_depIdxs = nil
}
