// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.0
// source: notify-service.proto

package notify

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotifyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmployerUuid string `protobuf:"bytes,1,opt,name=employer_uuid,json=employerUuid,proto3" json:"employer_uuid,omitempty"`
}

func (x *NotifyReq) Reset() {
	*x = NotifyReq{}
	mi := &file_notify_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyReq) ProtoMessage() {}

func (x *NotifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_notify_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyReq.ProtoReflect.Descriptor instead.
func (*NotifyReq) Descriptor() ([]byte, []int) {
	return file_notify_service_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyReq) GetEmployerUuid() string {
	if x != nil {
		return x.EmployerUuid
	}
	return ""
}

type VacancyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VacancyUuid string `protobuf:"bytes,1,opt,name=vacancy_uuid,json=vacancyUuid,proto3" json:"vacancy_uuid,omitempty"`
}

func (x *VacancyReq) Reset() {
	*x = VacancyReq{}
	mi := &file_notify_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VacancyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VacancyReq) ProtoMessage() {}

func (x *VacancyReq) ProtoReflect() protoreflect.Message {
	mi := &file_notify_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VacancyReq.ProtoReflect.Descriptor instead.
func (*VacancyReq) Descriptor() ([]byte, []int) {
	return file_notify_service_proto_rawDescGZIP(), []int{1}
}

func (x *VacancyReq) GetVacancyUuid() string {
	if x != nil {
		return x.VacancyUuid
	}
	return ""
}

type EmployerResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmployerUuid string `protobuf:"bytes,1,opt,name=employer_uuid,json=employerUuid,proto3" json:"employer_uuid,omitempty"`
}

func (x *EmployerResp) Reset() {
	*x = EmployerResp{}
	mi := &file_notify_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployerResp) ProtoMessage() {}

func (x *EmployerResp) ProtoReflect() protoreflect.Message {
	mi := &file_notify_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployerResp.ProtoReflect.Descriptor instead.
func (*EmployerResp) Descriptor() ([]byte, []int) {
	return file_notify_service_proto_rawDescGZIP(), []int{2}
}

func (x *EmployerResp) GetEmployerUuid() string {
	if x != nil {
		return x.EmployerUuid
	}
	return ""
}

var File_notify_service_proto protoreflect.FileDescriptor

var file_notify_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a,
	0x13, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2d, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a, 0x09, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65,
	0x71, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x72, 0x5f, 0x75, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79,
	0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x22, 0x2f, 0x0a, 0x0a, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63,
	0x79, 0x52, 0x65, 0x71, 0x12, 0x21, 0x0a, 0x0c, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x5f,
	0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x76, 0x61, 0x63, 0x61,
	0x6e, 0x63, 0x79, 0x55, 0x75, 0x69, 0x64, 0x22, 0x33, 0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x6c, 0x6f,
	0x79, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x6d, 0x70, 0x6c, 0x6f,
	0x79, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x32, 0xa1, 0x01, 0x0a,
	0x13, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x41, 0x70,
	0x70, 0x6c, 0x69, 0x65, 0x64, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x73, 0x42,
	0x79, 0x4e, 0x6f, 0x74, 0x79, 0x12, 0x12, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x3e, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x72, 0x42,
	0x79, 0x56, 0x61, 0x63, 0x12, 0x13, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x56,
	0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x42, 0x12, 0x5a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f, 0x6e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_notify_service_proto_rawDescOnce sync.Once
	file_notify_service_proto_rawDescData = file_notify_service_proto_rawDesc
)

func file_notify_service_proto_rawDescGZIP() []byte {
	file_notify_service_proto_rawDescOnce.Do(func() {
		file_notify_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_notify_service_proto_rawDescData)
	})
	return file_notify_service_proto_rawDescData
}

var file_notify_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_notify_service_proto_goTypes = []any{
	(*NotifyReq)(nil),     // 0: service.NotifyReq
	(*VacancyReq)(nil),    // 1: service.VacancyReq
	(*EmployerResp)(nil),  // 2: service.EmployerResp
	(*Notifications)(nil), // 3: models.Notifications
}
var file_notify_service_proto_depIdxs = []int32{
	0, // 0: service.NotificationService.GetAllAppliedCandidatesByNoty:input_type -> service.NotifyReq
	1, // 1: service.NotificationService.GetEmployerByVac:input_type -> service.VacancyReq
	3, // 2: service.NotificationService.GetAllAppliedCandidatesByNoty:output_type -> models.Notifications
	2, // 3: service.NotificationService.GetEmployerByVac:output_type -> service.EmployerResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notify_service_proto_init() }
func file_notify_service_proto_init() {
	if File_notify_service_proto != nil {
		return
	}
	file_notify_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_notify_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notify_service_proto_goTypes,
		DependencyIndexes: file_notify_service_proto_depIdxs,
		MessageInfos:      file_notify_service_proto_msgTypes,
	}.Build()
	File_notify_service_proto = out.File
	file_notify_service_proto_rawDesc = nil
	file_notify_service_proto_goTypes = nil
	file_notify_service_proto_depIdxs = nil
}
